### ISSUE TITLE
GKE: no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by adamzr** [ckt114/kubeswitch#2]
Trying to use Kubeswitch with GKE and I get this error trying to switch namespaces:

`no Auth Provider found for name "gcp"`

**Comment by ckt114** [comment]
@adamzr That error seems like an issue with your kube config file. Can you test using that kube config file without using Kubeswitch and see if you can get namespaces? Do an `export KUBECONFIG=/path/to/config` then `kubectl get ns`. Looks like for that `gcp` context you don’t have an authentication method attached to it.

**Comment by adamzr** [comment]
@trankchung I didn't have KUBECONFIG set. I set it. Then I ran `kubectl get ns` which worked fine.  Kubeswitch still gives me the same error.

**Comment by ghost** [comment]
@adamzr Do you mind try the latest version?

**Comment by adamzr** [comment]
Still doesn't work:
```
$ kubeswitch --version
v0.2.3
$ kubeswitch ns
no Auth Provider found for name "gcp"

```

**Comment by ghost** [comment]
Once in a Kubeswitch session, can you `cat $KUBECONFIG` and paste the content here? You can mask out sensitive info. I want to see the auth section of the config.

**Comment by adamzr** [comment]
```

**Comment by adamzr** [comment]
```

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED LONG BASE64 LOOKING STRING>
    server: https://<REDACTED IP>
  name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
- cluster:
    certificate-authority-data: <REDACTED LONG BASE64 LOOKING STRING>
    server: https://<REDACTED IP>
  name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
- cluster:
    certificate-authority-data: <REDACTED LONG BASE64 LOOKING STRING>
    server: https://<REDACTED IP>
  name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
contexts:
- context:
    cluster: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
    namespace: <REDACTED CLUSTER NAME>
    user: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  name: <REDACTED CLUSTER NAME>
- context:
    cluster: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
    user: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  name: <REDACTED CLUSTER NAME>
- context:
    cluster: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
    user: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  name: <REDACTED CLUSTER NAME>
current-context: <REDACTED CLUSTER NAME>
kind: Config
preferences: {}
users:
- name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  user:
    auth-provider:
      config:
        access-token: <REDACTED ACCESS TOKEN>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/<REDACTED>/google-cloud-sdk/bin/gcloud
        expiry: "2021-02-15T17:58:56Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  user:
    auth-provider:
      config:
        access-token: <REDACTED ACCESS TOKEN>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/<REDACTED>/google-cloud-sdk/bin/gcloud
        expiry: "2021-02-15T20:37:24Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_<REDACTED CLUSTER NAME>_us-west1-c_<REDACTED CLUSTER NAME>
  user:
    auth-provider:
      config:
        access-token: <REDACTED ACCESS TOKEN>
        cmd-args: config config-helper --format=json
        cmd-path: /Users/<REDACTED>/google-cloud-sdk/bin/gcloud
        expiry: "2021-01-19T02:46:23Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

```
